# Note that we are hardcoding the bucket name here.
# This would make not possible to reuse the code as-it-is. 

apiVersion: ark.heptio.com/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: heptio-ark
spec:
  provider: aws
  objectStorage:
    bucket: ark-prod-us-west-2
  config:
    region: us-west-2
    kmsKeyId: alias/ark-prod-us-west-2
