apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: heptio-ark
  name: ark
  labels:
    k8s-app: ark
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: ark
        k8s-app: ark
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::320464205386:role/ark-role-prod-us-west-2
    spec:
      restartPolicy: Always
      serviceAccountName: ark
      containers:
        - name: ark
          image: gcr.io/heptio-images/ark:v0.10.1
          ports:
            - name: metrics
              containerPort: 8085
          command:
            - /ark
          args:
            - server
          volumeMounts:
            - name: plugins
              mountPath: /plugins
          env:
            - name: AWS_CLUSTER_NAME
              value: kubernetes-prod-us-west-2
      volumes:
        - name: plugins
          emptyDir: {}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ark
  name: ark
  namespace: heptio-ark
spec:
  endpoints:
  - interval: 60s
    port: metrics
    scheme: http
  jobLabel: k8s-ark
  selector:
    matchLabels:
      k8s-app: ark
---
apiVersion: v1
kind: Service
metadata:
  name: ark
  labels:
    name: ark
    k8s-app: ark
  namespace: heptio-ark
spec:
  selector:
    k8s-app: ark
  ports:
  - name: metrics
    protocol: TCP
    port: 8085
  clusterIP: None


