apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: prometheus-general
    role: alert-rules
  name: mongodb-rules
  namespace: monitoring
spec:
  groups:
  - name: mongodb.rules
    rules:
    - alert: MongoDB_replicaSet_missing_members
      annotations:
        message: 'MongoDB replicaSet has less than 3 members'
      expr: |
        mongodb_mongod_replset_number_of_members < 3
      for: 5m
      labels:
        severity: critical

