---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: codebuild-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: codebuild-deployer
rules:
- apiGroups: ["","extensions","apps", "networking.k8s.io"]
  resources: ["pods","ingresses","services","namespaces","deployments","configmaps"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codebuild-deployer
  namespace: dinopark-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codebuild-deployer
subjects:
- kind: ServiceAccount
  name: codebuild-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codebuild-deployer
  namespace: sso-dashboard-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codebuild-deployer
subjects:
- kind: ServiceAccount
  name: codebuild-deployer
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: codebuild-deployer
  namespace: sso-dashboard-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: codebuild-deployer
subjects:
- kind: ServiceAccount
  name: codebuild-deployer
  namespace: default
