apiVersion: batch/v1
kind: CronJob
metadata:
  name: dino-park-packs-notify-cron
  namespace: dinopark-prod
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - curl -X POST dino-park-packs-service/internal/notify/all
            image: curlimages/curl
            imagePullPolicy: Always
            name: dino-park-packs-notify-cron
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 12 * * * '
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2023-05-30T12:00:00Z"
  lastSuccessfulTime: "2023-05-30T12:00:08Z"
