apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-mozdef
  namespace: logging
  labels:
    k8s-app: fluentd-mozdef
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-mozdef
  template:
    metadata:
      labels:
        k8s-app: fluentd-mozdef
        kubernetes.io/cluster-service: "true"
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::320464205386:role/fluentd-mozdef-prod-us-west-2
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: thesmoothoperator/v1.3-fluent-plugin-sns:3.2.5
        imagePullPolicy: Always
        env:
        - name: FLUENT_UID
          value: "0"
        - name: FLUENTD_SYSTEMD_CONF
          value: "disable"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
