kind: ConfigMap
metadata:
  name: fluentd-extra-conf
  namespace: logging
apiVersion: v1
data:
  audit.conf: |+
    <source>
      @type tail
      @id audit_log
      path /var/log/audit/audit.log
      pos_file /var/log/audit-log.pos
      tag auditd
    </source>

