kind: ConfigMap
metadata:
  name: fluentd-extra-conf
  namespace: logging
apiVersion: v1
data:
  audisp-json.conf: |+
    <source>
      @type tail
      @id audit_log
      path /var/log/audit-json.log
      pos_file /var/log/audit-json.log.pos
      tag audisp-json
      <parse>
        @type json
      </parse>
    </source>

