apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: ""
  creationTimestamp: null
  labels:
    io.kompose.service: memcached
  name: memcached
  namespace: mozillians-dev
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 11211
    targetPort: 0
  selector:
    io.kompose.service: memcached
status:
  loadBalancer: {}
